export const partnerLogos = [
    'binance.svg',
    'bybit.png',
    'coinbase.webp',
    'kucoin.png',
    'coingate.webp',
    'okyx.png',
    'htx.png',
    'moonpay.svg',
    // 'circle.svg',
    'falconx.svg',
    'anchor.png',
    'trusttoken.svg',
    'localbitcoins.webp',
    'genesis.webp',
    'bitflyer.webp',
    'stellar.webp',
    'paysafe.webp',
    'mourocapital.webp',
    'bitgo.webp',
    // 'wirex.webp',
]